bgrecommender/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recommender.urls', namespace='recommender'))
]

recommender/urls.py
from django.urls import path
from . import views
app_name = 'recommender'

urlpatterns = [
    # post views
    path('', views.game_list, name='game_list'),
    path('type/<int:id>/', views.gametype_view, name='gametype_view'),
    path('category/<int:id>/', views.category_view, name='category_view'),
    path('mechanic/<int:id>/', views.mechanic_view, name='mechanic_view'),
    path('game/<int:id>/', views.game_view, name='game_detail'),
]

recommender/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify


class GameType(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(max_length=30, default='')

    class Meta:  
        ordering = ['-title']  # Creating a sort order from newest to oldest
        indexes = [models.Index(fields=['-title']),]  # This will improve performance for queries filtering or ordering results by this field
    def __str__(self):  # for human-readable representation of the object
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=50)
    class Meta:  
        ordering = ['-title']  # Creating a sort order from newest to oldest
        indexes = [models.Index(fields=['-title']),]  # This will improve performance for queries filtering or ordering results by this field
    def __str__(self):  # for human-readable representation of the object
        return self.title

class Mechanic(models.Model):
    title = models.CharField(max_length=50)
    class Meta:  
        ordering = ['title']  # Creating a sort order from newest to oldest
        indexes = [models.Index(fields=['-title']),]  # This will improve performance for queries filtering or ordering results by this field
    def __str__(self):  # for human-readable representation of the object
        return self.title

class Designer(models.Model):
    title = models.CharField(max_length=50)
    class Meta:  
        ordering = ['-title']  # Creating a sort order from newest to oldest
        indexes = [models.Index(fields=['-title']),]  # This will improve performance for queries filtering or ordering results by this field
    def __str__(self):  # for human-readable representation of the object
        return self.title

class Artist(models.Model):
    title = models.CharField(max_length=50)
    class Meta:  
        ordering = ['-title']  # Creating a sort order from newest to oldest
        indexes = [models.Index(fields=['-title']),]  # This will improve performance for queries filtering or ordering results by this field
    def __str__(self):  # for human-readable representation of the object
        return self.title


class Game(models.Model):
    gameid = models.IntegerField()
    title = models.CharField(max_length=150)
    year = models.IntegerField(blank=True, null=True)
    num_voters = models.IntegerField(blank=True, null=True) # number of voters
    rating_geek = models.FloatField(blank=True, null=True)
    rating_avg = models.FloatField(blank=True, null=True)
    gametype = models.ManyToManyField(GameType, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    mechanic = models.ManyToManyField(Mechanic,blank=True)
    designer = models.ManyToManyField(Designer, blank=True)
    artist = models.ManyToManyField(Artist, blank=True)
    playingtime = models.IntegerField(blank=True, null=True)
    minplayers = models.IntegerField(blank=True, null=True)
    maxplayers = models.IntegerField(blank=True, null=True)
    minage = models.IntegerField(blank=True, null=True)
    weight = models.FloatField(blank=True, null=True)
    image_url = models.URLField(blank=True)

    class Meta:  
        ordering = ['-title']  # Creating a sort order from newest to oldest
        indexes = [models.Index(fields=['-title']),]  # This will improve performance for queries filtering or ordering results by this field
    def __str__(self):  # for human-readable representation of the object
        return self.title

class User(models.Model):
    name = models.CharField(max_length=50)
    games_rec = models.ManyToManyField(Game, blank=True)
    class Meta:  
        ordering = ['-name']  # Creating a sort order from newest to oldest
        indexes = [models.Index(fields=['-name']),]  # This will improve performance for queries filtering or ordering results by this field
    def __str__(self):  # for human-readable representation of the object
        return self.name


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, blank=True)
    rating = models.IntegerField()

    def __str__(self):
        return f"{self.user}: {self.rating}"

recommender/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(max_length=50, initial="your name")

class EmailForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'placeholder': 'Name'}))
    email = forms.EmailField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Message'}))

recommender/views.py
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail  # for sending email message
from .models import Game, GameType, User, Category, Mechanic
from .forms import UserForm, EmailForm


def game_list(request):
    games = Game.objects.all()  # all games
    gametypes = GameType.objects.all()
    
    # Sending a message to my email
    sent = False 
    if request.method == 'POST':
        # Form was submitted
        form_email = EmailForm(request.POST)
        if form_email.is_valid():
            # Form fields passed validation
            cd = form_email.cleaned_data
            subject = f"A message from {cd['name']} from mysite"
            message = f"{cd['name']} {cd['email']}\n\n{cd['message']}"
            send_mail(subject, message, 'm.kolbasov@gmail.com',
                      ['m.kolbasov@gmail.com'])
            sent = True
    else:
        form_email = EmailForm()

    context = {
        'games': games,
        'gametypes': gametypes,
        'sent': sent,
        'form_email': form_email,
        'form': UserForm(),
    }

    username = request.GET.get('username')  # from index.html form
    if username:
        try:
            user = User.objects.get(name=username)  # get above user from User model
            recommended_games = user.games_rec.all()
            context['user'] = user
            context['recommended_games'] = recommended_games
        except User.DoesNotExist:
            context['error_message'] = f"User '{username}' not found."
    
    return render(request, 'recommender/index.html', context)


def gametype_view(request, id):
    gametype = get_object_or_404(GameType, id=id)
    games = Game.objects.filter(gametype__id=id).order_by('-rating_geek')
    context = {
        'games': games,
        'gametype': gametype,
    }
    return render(request, 'recommender/gametype.html', context)

def category_view(request, id):
    category = get_object_or_404(Category, id=id)
    games = Game.objects.filter(category__id=id).order_by('-rating_geek')
    context = {
        'games': games,
        'category': category,
    }
    return render(request, 'recommender/category.html', context)

def mechanic_view(request, id):
    mechanic = get_object_or_404(Mechanic, id=id)
    games = Game.objects.filter(mechanic__id=id).order_by('-rating_geek')
    context = {
        'games': games,
        'mechanic': mechanic,
    }
    return render(request, 'recommender/mechanic.html', context)

def game_view(request, id):
    game = get_object_or_404(Game, id=id)
    gametypes = GameType.objects.all()
    context = {
        'game': game,
        'gametypes': gametypes,
    }
    return render(request, 'recommender/gamedetail.html', context)

recommender/templates/recommender/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ category.title }}</title>
</head>

<style>
    .game-table {
        border-collapse: collapse;
    }

    .game-table th,
    .game-table td {
        border: 1px solid black;
        padding: 8px;
        text-align: center;
    }

    .game-table img {
        max-width: 50px;
        max-height: 50px;
    }
</style>

<body>
    <a href="{% url 'recommender:game_list' %}">Home</a>
    <h1>{{ category.title }}</h1>
    
    <table class="game-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>Title</th>                
                <th>Year</th>
                <th>Geek Rating</th>
                <th>Average Rating</th>

            </tr>
        </thead>
        <tbody>
            {% for game in games %}
                {% with forloop.counter as game_number %}
                <tr>
                    <td>{{ game_number }}</td>
                    <td><img src="{{ game.image_url }}" alt="{{ game.title }}"></td>
                    <td>{{ game.title }}</td>
                    
                    <td>{{ game.year }}</td>
                    <td>{{ game.rating_geek }}</td>
                    <td>{{ game.rating_avg }}</td>
                </tr>
                {% endwith %}
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

recommender/templates/recommender/gamedetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'css/game.css' %}">
    
    <!-- Fonts -->
    <!-- Awesome Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Baloo+Da+2:wght@400;500;600;700;800&family=Josefin+Slab:ital,wght@0,400;0,600;1,300;1,400;1,600&family=Muli:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap"
      rel="stylesheet"
    />
    <!-- End of Fonts -->

    <title>{{ game.title }}</title>
</head>

<body>
   
    
    <section class="game-details">
        <div class="image-container">
            <img src="{{ game.image_url }}" alt="{{ game.title }}" class="game-image">
        </div>
        <div class="info-container">
            <a href="{% url 'recommender:game_list' %}">Home</a>
            <h1>{{ game.title }}</h1>
            <h2>{{ game.year }}</h2>
            <h2>Type:</h2>
            {% for gametype in game.gametype.all %}
                <a href="{% url 'recommender:gametype_view' gametype.id %}">{{ gametype.title }}</a>
                
            {% endfor %}
            <h2>Category:</h2>
            {% for cat in game.category.all %}
                <div><a href="{% url 'recommender:category_view' cat.id %}">{{ cat }}</a></div>
            {% endfor %}
            <h2>Mechanic:</h2>
            {% for mech in game.mechanic.all %}
                <div><a href="{% url 'recommender:mechanic_view' mech.id %}">{{ mech }}</a></div>
            {% endfor %}
        </div>
    </section>
    
    
    

    
</body>
</html>

recommender/templates/recommender/gametype.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ gametype.title }}</title>
</head>

<style>
    .game-table {
        border-collapse: collapse;
    }

    .game-table th,
    .game-table td {
        border: 1px solid black;
        padding: 8px;
        text-align: center;
    }

    .game-table img {
        max-width: 50px;
        max-height: 50px;
    }
</style>

<body>
    <a href="{% url 'recommender:game_list' %}">Home</a>
    <h1>{{ gametype.title }}</h1>
    
    <table class="game-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>Title</th>                
                <th>Year</th>
                <th>Geek Rating</th>
                <th>Average Rating</th>

            </tr>
        </thead>
        <tbody>
            {% for game in games %}
                {% with forloop.counter as game_number %}
                <tr>
                    <td>{{ game_number }}</td>
                    <td><img src="{{ game.image_url }}" alt="{{ game.title }}"></td>
                    <td>{{ game.title }}</td>
                    
                    <td>{{ game.year }}</td>
                    <td>{{ game.rating_geek }}</td>
                    <td>{{ game.rating_avg }}</td>
                </tr>
                {% endwith %}
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

recommender/templates/recommender/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Fonts -->
    <!-- Awesome Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Baloo+Da+2:wght@400;500;600;700;800&family=Josefin+Slab:ital,wght@0,400;0,600;1,300;1,400;1,600&family=Muli:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap"
      rel="stylesheet"
    />
    <!-- End of Fonts -->

    <title>Boardgame Recommender</title>
</head>

<body>
    <div class="container">
        
        
        <!-- Navbar -->
        <nav class="navbar center sticky">
            <a href="{% url 'recommender:game_list' %}" class="navbar-link">Home</a>
            {% for gametype in gametypes %}
                <a href="{% url 'recommender:gametype_view' gametype.id %}" class="navbar-link">{{ gametype.title }}</a>
            {% endfor %}

        </nav>
        <!-- End of Navbar -->

        <!-- Section 1: Rec Games -->
        <section class="section-3" id="section-3">
            <form method="GET" action="{% url 'recommender:game_list' %}">
                <div class="section-heading">Enter your username from <a href="https://boardgamegeek.com/">bgg</a>:  {{ form.username }}</div>
                <p style="font-size: 18px;">Only for users who rated at least 7 games</p>
                <p style="font-size: 18px;">The recommendations are only for the games published since 2015 </p>
                <input type="submit" value="Submit" class="contact-form-btn">
                <div>{{ error_message }}</div>
                
            </form>
            
            <h1 class="section-heading">Your Recommendations</h1>
            <div class="projects-wrapper center">
                {% for game in recommended_games %}
                <a href="{% url 'recommender:game_detail' game.id %}" class="project center" target="_blank">
                    <div class="project-text">
                        
                    </div>
                    <img src="{{ game.image_url }}" alt="{{ game.title }}" class="project-img" style="width: 200px; height: 200px;">
                </a>
                {% endfor %}                
            </div>
        </section>    
        <!-- End of Section 1 -->

        <!-- Section 4: Contact -->
        <section class="section-4" id="section-4">
            <h1 class="section-4-heading section-heading">Contact Me</h1>
            {% if sent %}
                <h1 class="section-4-heading section-heading">E-mail was successfully sent</h1>
            {% else %}
                <form class="contact-form center" method="post">
                    {% csrf_token %}
                    {{ form_email.name }}
                    {{ form_email.email }}
                    {{ form_email.message }}
                    <input type="submit" value="Submit" class="contact-form-btn">
                </form>
            {% endif %}
            
        </section>
        <!-- End of Section 4 -->

        <!-- Section 5: Footer -->
        <footer class="section-5 center">
            <div class="social-media">
                <a href="https://github.com/axci?tab=repositories" class="social-media-link"><i class="fab fa-github-square"></i></a>
                <!--<a href="#none" class="social-media-link"><i class="fab fa-youtube"></i></a>-->
                <a href="https://twitter.com/maxim_kolbasov" class="social-media-link"><i class="fab fa-twitter-square"></i></a>
            </div>
            <p class="copyright">
                Copyright &copy; Maxim Kolbasov. All Rights Reserved.
            </p>
        </footer>
        <!-- End of Section 5 -->
    </div>

    
</body>

</html>

recommender/templates/recommender/mechanic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ mechanic.title }}</title>
</head>

<style>
    .game-table {
        border-collapse: collapse;
    }

    .game-table th,
    .game-table td {
        border: 1px solid black;
        padding: 8px;
        text-align: center;
    }

    .game-table img {
        max-width: 50px;
        max-height: 50px;
    }
</style>

<body>
    <a href="{% url 'recommender:game_list' %}">Home</a>
    <h1>{{ mechanic.title }}</h1>
    
    <table class="game-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>Title</th>                
                <th>Year</th>
                <th>Geek Rating</th>
                <th>Average Rating</th>

            </tr>
        </thead>
        <tbody>
            {% for game in games %}
                {% with forloop.counter as game_number %}
                <tr>
                    <td>{{ game_number }}</td>
                    <td><img src="{{ game.image_url }}" alt="{{ game.title }}"></td>
                    <td>{{ game.title }}</td>
                    
                    <td>{{ game.year }}</td>
                    <td>{{ game.rating_geek }}</td>
                    <td>{{ game.rating_avg }}</td>
                </tr>
                {% endwith %}
            {% endfor %}
        </tbody>
    </table>
</body>
</html>